# Generated by Django 4.2.3 on 2024-07-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salon_menu_salon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salon_menu',
        ),
    ]
