# Generated by Django 4.2.3 on 2024-09-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_service1_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
