# Generated by Django 4.2.3 on 2024-09-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='usename',
            new_name='username',
        ),
    ]
