# Generated by Django 4.2.3 on 2024-08-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='salon_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.IntegerField()),
                ('phone_no', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='closing_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='no_of_barbers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='no_of_chairs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='opening_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
