# Generated by Django 4.2.3 on 2024-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_rename_usename_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('admin', 'admin')], default='customer', max_length=200),
        ),
    ]
